### ISSUE TITLE
Invalid constructor parameter type

### ISSUE THREAD

**Issue by mudrd8mz** [tmas0/moodle-tool_autorestore#1]
Spotted during the iinstallation of the plugin with the developer debugging on:

```
Notice: Array to string conversion in /lib/adminlib.php on line 2617
Notice: Array to string conversion in /lib/adminlib.php on line 2626
```

These are caused by invalid type of the parameter passed to `admin_setting_configcheckbox::__construct()` in your settings.php file. Note that `$defaultsetting` is supposed to be a string (as documented) whereas you pass an array.

You maybe wanted to use `admin_setting_configcheckbox_with_lock` class.

**Comment by RicardoUIB** [comment]
Thanks! issue is corrected
